# For more information: https://laravel.com/docs/api
version: '3'
services:

  app:
    image: aristidesbneto/php7.4
    container_name: app
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    networks:
      - api

  mysql:
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    networks:
      - api

networks:
  api:
    driver: bridge
